import { HttpStatus } from '@nestjs/common';

export interface IGeneralErrorShape {
  message: string;
  errorCode: string;
  description?: string;
  statusCode?: HttpStatus;
  stackTrace?: any;
  logData?: any;
  data?: any;
}

export enum ErrorCode {
  WALLET_ALREADY_EXISTS = '001',
  CANNOT_CREATE_WALLET = '002',
  INTERNAL_SERVER_ERROR = '003',
  GENERAL_UNAUTHORIZED_EXCEPTION = '004',
  GENERAL_VALIDATION_EXCEPTION = '005',
  ACCESS_TOKEN_HEADER_NOT_PROVIDED = '006',
  JWT_EXPIRED = '007',
  NOT_VALID_JWT = '008',
  SERVICE_UNAVAILABLE = '009',
  INVALID_KIPLE_SIGNATURE = '010',
  WALLET_NOT_FOUND = '011',
  BAD_GATEWAY = '012',
  GATEWAY_TIMEOUT = '013',
  GET_ACCOUNTS_PROFILE_FAILED = '014',
  CREDIT_CARD_NOT_FOUND = '015',
  KIPLE_TRANSACTION_FAILED = '016',
  TRANSACTION_NOT_FOUND = '017',
  TRANSACTION_ALREADY_SAVED = '018',
  WALLET_AUTO_TOPUP_SETTINGS_NOT_FOUND = '019',
  WALLET_AUTO_TOPUP_INACTIVE = '020',
  INVALID_KIPLE_PIN_TOKEN = '021',
  GENERAL_KIPLE_ERROR = '022',
  KIPLE_RESPONSE_TIMEOUT = '023',
  KIPLE_RESPONSE_BAD_GATEWAY = '024',
  INVALID_KIPLE_PIN = '025',
  RESET_PIN_CODE_EXPIRED = '026',
  RESET_PIN_WRONG_CODE = '027',
  NOT_VALID_OTP = '028',
  MAXIMUM_BALANCE_EXCEEDED = '029',
  LESS_THAN_MIMIMUM_BALANCE = '030',
  NOT_VALID_PAYMENT_METHOD = '031',
  TRANSACTION_SHOULD_HAVE_EXPIRY_DATE = '032',
  SMARTPAY_ERROR = '033',
  INSUFFICIENT_BALANCE = '034',
  FUEL_VOUCHER_REQUIRED = '035',
  EMAIL_FORMAT_IS_NOT_VALID = '036',
  EMAIL_IS_ALREADY_TAKEN = '037',
  KIPLE_SIGNATURE_REQUIRED = '038',
  PHONE_IS_ALREADY_TAKEN = '039',
  EMAIL_OR_PHONE_REQUIRED = '040',
  CUSTOMER_CHARGE_LIMIT = '041',
  BALANCE_LIMIT_EXCEEDED = '042',
  SWITCH_ERROR = '043',
  ORDERS_ERROR = '044',
  CUSTOMER_MAX_TRANSACTION_LIMIT = '045',
  CUSTOMER_TRANSACTION_AMOUNT_LIMIT = '046',
  BLACKLIST_ERROR = '047',
}

export enum MongoDbError {
  DUPLICATE_KEY_ERROR = 11000,
}
