service:
  name: npm_package_name
  description: Base nestjs mongo
  node_env: NODE_ENV
  baseUrl: APP_PREFIX
  docsBaseUrl: APP_DOCS
  jwt_access_token_secret: JWT_ACCESS_TOKEN_SECRET
  jwt_access_token_expiration_time: JWT_ACCESS_TOKEN_EXPIRATION_TIME
  jwt_refresh_token_secret: JWT_REFRESH_TOKEN_SECRET
  jwt_refresh_token_expiration_time: JWT_REFRESH_TOKEN_EXPIRATION_TIME
  api_version: npm_package_version
  app_version: npm_package_version

server:
  host: localhost
  port: 3000
  hostname: localhost:3000
  swaggerSchema: http

mongodb:
  uri: MONGODB_URI

redis:
  standalone:
    host: 127.0.0.1
    port: 6379
    pass: null
    url: redis://localhost:6379
  sendEmailQueue: 'sendEmailQueue'
  sendNotificationsQeueu: 'sendNotificationsQeueu'

mail:
  account: MAIL_ACCOUNT
  password: MAIL_PASSWORD
  from: MAIL_FROM
  service: MAIL_SERVICE
  enable: MAIL_ENABLE

logger:
  enabled: true

notification:
  publicKey: VITE_WEB_PUSH_PUBLIC
  privateKey: VITE_WEB_PUSH_PRIVATE
